# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\chait\OneDrive\Desktop\college predictor\cp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 879)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(-6, -21, 1171, 231))
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 210, 551, 581))
        self.label_4.setStyleSheet("border:2px solid rgb(85,85,255,255);\n"
"border-image: url(:/newPrefix2/college.jfif);\n"
"border-top-left-radius:90px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(550, 210, 561, 581))
        self.label.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(218, 218, 218);\n"
"border-bottom-right-radius:90px;\n"
"border:2px solid rgb(134,134,134);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(570, 220, 141, 31))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(570, 380, 161, 31))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(570, 340, 141, 31))
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(570, 300, 141, 31))
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(570, 260, 141, 31))
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(740, 220, 321, 31))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"  border:2px solid rgb(134,134,134);\n"
"  border-radius:20px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(740, 380, 321, 31))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"  border:2px solid rgb(134,134,134);\n"
"  border-radius:20px;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(740, 340, 321, 31))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"  border:2px solid rgb(134,134,134);\n"
"  border-radius:20px;\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(740, 300, 321, 31))
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"  border:2px solid rgb(134,134,134);\n"
"  border-radius:20px;\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(740, 260, 321, 31))
        self.lineEdit_5.setStyleSheet("QLineEdit{\n"
"  border:2px solid rgb(134,134,134);\n"
"  border-radius:20px;\n"
"}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(840, 460, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {    \n"
"    border-radius:25px;\n"
"    border:2px solid rgb(0,0,255,255);\n"
"    background-color: rgb(85, 170, 255);\n"
"    color:rgba(85,85,255)   \n"
"}\n"
"QPushButton:hover {\n"
"    background-color :rgb(50,110,255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(100,170,255);\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(740, 420, 321, 31))
        self.comboBox.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(128, 124, 124, 255), stop:0.985075 rgba(116, 201, 255, 255));\n"
"border:2px solid rgb(134,134,134);\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setItemText(19, "")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(570, 420, 141, 31))
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 300, 551, 251))
        self.label_10.setStyleSheet("background-color:rgba(0,0,0,75);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(100, 290, 321, 61))
        self.label_11.setStyleSheet("color:rgba(255,255,255,210);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 310, 551, 181))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(0, 120, 1111, 31))
        self.label_13.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(0, 840, 1121, 16))
        self.label_14.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(0, 800, 1121, 31))
        self.label_15.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(0, 160, 1111, 16))
        self.label_16.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(600, 520, 451, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"  background-color:rgb(200,200,200);\n"
"  color:rgb(170,85,127);\n"
"  border-style:solid;\n"
"  border-radius:10px;\n"
"  text-align:center;\n"
"}\n"
"QProgressBar::chunk{\n"
"  border-radius:10px;\n"
"  background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0\n"
"rgba(185,105,254,255), stop:1 rgba(106,211,255,255));\n"
"}\n"
"")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(600, 550, 241, 20))
        self.label_17.setObjectName("label_17")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(580, 570, 511, 171))
        self.listWidget.setObjectName("listWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/banner.png\"/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">10th Marks</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">12th Division</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">AIEEE Rank</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Year</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">12th Marks</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Predict College"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Delhi"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Tamil Nadu"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Gujarat"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Andhra Pradesh"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Karnataka"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Telangana"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Rajasthan"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Chhattisgarh"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Kerala"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Assam"))
        self.comboBox.setItemText(10, _translate("MainWindow", "West Bengal"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Uttar Pradesh"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Jammu"))
        self.comboBox.setItemText(13, _translate("MainWindow", "Maharashtra"))
        self.comboBox.setItemText(14, _translate("MainWindow", "Madhya Pradesh"))
        self.comboBox.setItemText(15, _translate("MainWindow", "Jharkhand"))
        self.comboBox.setItemText(16, _translate("MainWindow", "Goa"))
        self.comboBox.setItemText(17, _translate("MainWindow", "Himachal Pradesh"))
        self.comboBox.setItemText(18, _translate("MainWindow", "Punjab"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">State</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600;\">College predictor</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Hi,</span></p><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">welcome to college predictor.</span></p><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">This application will predict the colleges for</span></p><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">students based on the their Marks and Ranks</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_17.setText(_translate("MainWindow", "We will soon display the colleges"))
import banner_rc
import college_rc
import lace_rc
import strip_rc
